name: Run Selenium Tests with Allure and HTML Report

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Verify Chrome installed
      run: google-chrome --version

    - name: Run Pytest with HTML and Allure reporting
      run: |
        pytest tests/ \
          --browser chrome \
          --headless \
          --html=reports/report.html \
          --self-contained-html \
          --alluredir=reports/allure-results

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
        tar -zxvf allure.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Generate Allure HTML Report
      run: |
        allure generate reports/allure-results -o reports/allure-report --clean

    - name: Upload Pytest HTML report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-html-report
        path: reports/report.html

    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: reports/allure-report
